#cloud-config
autoinstall:
  version: 1

  identity:
    realname: "Infra Server"
    hostname: ubuntu-infra
    username: infra

  ssh:
    install-server: true
    allow-pw: false

  ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFMdXF4V4Bqcg5/+eXU7YYc17bxL+xJrhwTQ8akkPTTZ infra@ETCASSINI24

  locale: pt_BR.utf8
  keyboard:
    layout: br
  timezone: "America/Sao_Paulo"

  packages:
    - git
    - curl
    - wget
    - build-essential
    - net-tools

    - ufw
    - fail2ban

    - wireguard

    - samba
    - smbclient
    - krb5-config
    - winbind

    - xfce4
    - xfce4-goodies
    - dbus-x11

    - xrdp

    - docker.io
    - docker-compose-plugin

  snaps: []

  updates: security

  late-commands:
    - curtin in-target -- apt update
    - curtin in-target -- apt upgrade -y

    - curtin in-target -- systemctl enable ssh

    # XFCE para XRDP
    - curtin in-target -- bash -c "echo startxfce4 > /home/infra/.xsession"
    - curtin in-target -- chown infra:infra /home/infra/.xsession

    # serviços
    - curtin in-target -- systemctl enable xrdp
    - curtin in-target -- systemctl enable docker

    # firewall
    - curtin in-target -- ufw allow 22/tcp
    - curtin in-target -- ufw allow 3389/tcp
    - curtin in-target -- ufw allow 51820/udp
    - curtin in-target -- ufw enable

  shutdown: reboot
